
services:
  db:
    image: mysql:8
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'new_dock'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    depends_on:
      - db
    environment:
      - MYSQL_DATABASE=new_dock
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - DB_HOST='%'

volumes:
  mysql_data:

